#!/usr/bin/env python3
"""Install Codex skill entry points without symlinks or copied workflow bodies."""

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
MARKER = "<!-- Generated by scripts/leo_setup.py; edit the canonical skill instead. -->"


def skill_metadata(path):
    """Read the plain/folded name and description used by Leo; no PyYAML needed."""
    content = path.read_text(encoding="utf-8-sig")
    if not content.startswith("---\n"):
        raise ValueError(f"Missing YAML frontmatter: {path}")
    header = content.split("---", 2)[1]
    fields = {}
    for key in ("name", "description"):
        match = re.search(rf"^{key}: *(.*)((?:\n[ \t]+[^\n]*)*)", header, re.M)
        if not match:
            raise ValueError(f"Missing {key}: {path}")
        value = match[1].strip()
        if value in (">", ">-", "|", "|-"):
            value = " ".join(line.strip() for line in match[2].splitlines()).strip()
        elif value.startswith('"'):
            value = json.loads(value)
        elif value.startswith("'") and value.endswith("'"):
            value = value[1:-1].replace("''", "'")
        fields[key] = value
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", fields["name"]):
        raise ValueError(f"Invalid skill name: {path}")
    if not fields["description"]:
        raise ValueError(f"Empty description: {path}")
    return fields


def canonical_skills(root):
    # Exact casing also avoids treating legacy, metadata-free skill.md files as skills on Windows.
    for directory in sorted((root / ".claude/skills").iterdir()):
        if directory.is_dir():
            for path in directory.iterdir():
                if path.name == "SKILL.md":
                    metadata = skill_metadata(path)
                    if metadata["name"] != directory.name:
                        raise ValueError(f"Skill name differs from directory: {path}")
                    yield directory.name, metadata


def wrapper(name, metadata, root=None):
    description = metadata["description"]
    # Codex's validator caps discovery descriptions; leave the canonical skill intact.
    if len(description) > 1024:
        description = description[:1021].rsplit(" ", 1)[0] + "..."
    if root is None:
        resolution = (
            "Resolve Leo's root as three directories above this skill directory "
            "(the directory containing `.agents` and `.claude`). "
            "Resolve from this file's actual path, not the shell's current directory."
        )
    else:
        resolution = (
            "First check the current working directory and its ancestors for a Leo checkout "
            "containing both `scripts/leo_runtime.py` and `.claude/skills/start-session/SKILL.md`. "
            "Use the nearest match so a second checkout or worktree uses its own context. "
            f"Otherwise use the registered Leo root: `{root.as_posix()}`. "
            "If that path no longer exists, report the stale installation; rerun "
            "`scripts/leo_setup.py --user` from the relocated checkout. Do not guess a root."
        )
    return f'''---
name: {name}
description: {json.dumps(description, ensure_ascii=False)}
---

{MARKER}

# Leo: {name}

{resolution}

Read `AGENTS.md` in the resolved Leo root unless it is already loaded for that checkout.
Read `.codex/LEO.md` and `system/instincts/INDEX.md` there if absent from context;
read the full instincts relevant to this request before giving substantive advice.
Then read and follow `.claude/skills/{name}/SKILL.md` there. That file is the
single source of truth; this entry point only makes it discoverable in Codex.
Resolve supporting references relative to the canonical skill directory. Resolve
Leo context paths and commands against the Leo root, using an explicit working
directory or `git -C` when the session started elsewhere. Never sync, stage, commit,
or push an unrelated repository because it happens to be the current directory.
Detect the actual OS and shell; translate shell-specific examples accordingly.
Tool permissions still apply when Leo is outside the task's writable workspace.
'''


def install(root, destination, user=False, check=False):
    """Preflight every destination; preserve unrelated skills and edited installations."""
    legacy = False
    if destination.is_symlink():
        legacy = not user and destination.resolve() == (root / ".claude/skills").resolve()
        if not legacy:
            raise ValueError(f"Refusing to replace a skill-directory symlink: {destination}")
    elif destination.is_file():
        legacy = not user and destination.read_text(encoding="utf-8").strip() == "../.claude/skills"
        if not legacy:
            raise ValueError(f"Not a skill directory: {destination}")

    pending = []
    skills = list(canonical_skills(root))
    for name, metadata in skills:
        path = destination / name / "SKILL.md"
        expected = wrapper(name, metadata, root if user else None)
        if not legacy:
            if path.parent.is_symlink() or path.is_symlink():
                raise ValueError(f"Refusing to overwrite a linked skill: {path}")
            if path.exists():
                actual = path.read_text(encoding="utf-8")
                if actual == expected:
                    continue
                if MARKER not in actual:
                    raise ValueError(f"Existing skill is not Leo-managed; preserved: {path}")
            elif path.parent.exists():
                raise ValueError(f"Existing skill folder is not Leo-managed; preserved: {path.parent}")
        pending.append((path, expected))

    if check:
        return len(skills), [str(path) for path, _ in pending]
    if legacy:
        # Remove only the known link/text stub itself; never its canonical target.
        destination.unlink()
    for path, content in pending:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return len(skills), [str(path) for path, _ in pending]


def main():
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--project", action="store_true", help="Generate portable repo entry points")
    group.add_argument("--user", action="store_true", help="Install skills for this OS user, from any folder")
    parser.add_argument("--check", action="store_true", help="Read-only check; exit 1 if installation needs updating")
    parser.add_argument("--skills-dir", type=Path, help="Override user destination (e.g. an isolated test home)")
    args = parser.parse_args()
    if args.skills_dir and not args.user:
        parser.error("--skills-dir requires --user")
    destination = ((args.skills_dir or Path.home() / ".agents/skills") if args.user
                   else ROOT / ".agents/skills").expanduser().absolute()
    try:
        count, changed = install(ROOT, destination, args.user, args.check)
    except (OSError, ValueError) as error:
        print(f"Leo setup: {error}", file=sys.stderr)
        return 2
    print(f"Leo root: {ROOT}")
    print(f"Codex skills: {destination}")
    print(f"{count} skills; {len(changed)} {'need updating' if args.check else 'updated'}.")
    if args.user and not args.check:
        print("Use $start-session or $end-session. Restart Codex if its skill picker is stale.")
    return int(args.check and bool(changed))


if __name__ == "__main__":
    raise SystemExit(main())
